myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('quanlitaisan/', include('quanlitaisan.urls')),
    path('', include('quanlitaisan.urls'))
]

quanlitaisan/urls.py
from django.urls import path, re_path
from . import views, api

app_name = 'quanlitaisan'

urlpatterns = [
  # path('', views.index, name = 'index'),
  path('', views.index_update, name = 'index_update'),
  path('details/<int:asset_id>', views.details, name = 'details'),
  path('maintain/<int:maintain_id>', views.maintains, name = 'maintains'),
  path('search/', views.search_items, name = 'search'),
  path('addItem/', views.add_asset, name = 'add_item'),
  path('addMaintain/', views.add_maintain, name = 'add_maintain'),
  path('assets/<int:page>', views.assets_list, name = 'assets_list'),
  path('remove/<int:asset_id>', views.remove_asset, name = 'remove_asset'),
  path('kiemke/', views.inspect_update, name = 'kiemke'),
  path('nhap/', views.nhap_hang_update, name = 'nhap_hang'),
  path('xuat/', views.xuat_hang_update, name = 'nhap_hang'),
  path('api/<str:asset_id>', api.json_detail, name = 'json_details'),
  path('api/search/<str:sw>', api.search, name = 'json_search'),
  path('api/export/', api.FileExport.csv_export, name = 'csv'),
  path('delete/<int:asset_id>', views.delete, name = 'delete_view'),
  path('signout', views.signout, name = 'signout_view'),
  path('accounts/login/', views.sign_in, name = 'sign_in_view'),
  path('assets/update/<int:asset_id>', views.update_asset, name = 'update'),
  path('profile/', views.display_profile, name = 'profile'),
  path('changepassword/', views.change_password, name = 'change_pass')
  # path('test', views.test, name= 'test'),
]

quanlitaisan/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class NhanVien(models.Model):
  DEFAULT_NV_ID = 7
  user =  models.OneToOneField(User, on_delete= models.CASCADE)
  name  =  models.CharField('Họ và tên', max_length = 40)
  # DOB   = models.DateField('Ngày tháng năm sinh')
  title = models.CharField('Chức vụ', max_length = 20)
  department = models.CharField('Phòng ban', max_length = 20)

  def __str__(self):
    return str(self.id) + "---" + self.name

class TaiSan(models.Model):
  LOAI_TAI_SAN = [
    ('VT', 'Vật tư'),
    ('TB', 'Thiết bị')
  ]

  HIEN_TRANG = [
    ('SD', 'Đang sử dụng'),
    ('BH', 'Bị hỏng'),
  ]
  
  DON_vI_TINH = [
    ('C', 'Cái'),
    ('Ch', 'Chiếc'),
    ('T', 'Tập'),
    ('KG', 'Kilogram'),
    ('ML', 'ml'),
    ('K', 'Khác')
  ]

  loai_tai_san       = models.CharField('loại tài sản', max_length = 2, choices = LOAI_TAI_SAN)
  ten_tai_san        = models.CharField('tên tài sản', max_length = 20)
  don_vi_tinh        = models.CharField('Đơn vị tính', max_length = 2, choices = DON_vI_TINH)
  so_luong           = models.PositiveIntegerField('Số lượng')
  ngay_su_dung       = models.DateField('ngày bắt đầu sử dụng')
  thoi_han_bao_hanh  = models.PositiveIntegerField('số năm bảo hành')
  thoi_gian_sd       = models.PositiveIntegerField('số năm sử dụng')
  tai_san_cha        = models.ForeignKey('self', on_delete = models.SET_NULL, null = True, blank = True,verbose_name = 'Thiết bị chứa')
  dia_diem           = models.CharField('Địa điểm', max_length = 20)
  hien_trang         = models.CharField('Hiện trạng', max_length = 2, choices = HIEN_TRANG)
  quan_ly            = models.ForeignKey(NhanVien, on_delete = models.SET_DEFAULT, default = NhanVien.DEFAULT_NV_ID)

  def __str__(self):
    ten_hien_thi = 'id :' + str(self.id) + '---'+ 'name: ' + self.ten_tai_san
    return ten_hien_thi
 
 
class LichSuBaoTri(models.Model):
  ngay_bao_tri    = models.DateField('Ngày Bảo Trì')
  tai_san_bao_tri = models.ForeignKey(TaiSan, on_delete = models.CASCADE, verbose_name = 'Tài sản bảo trì')
  tieu_de         = models.CharField('Tiêu đề', max_length = 30)
  noi_dung        = models.TextField('Nội dung bảo trì')

  def __str__(self):
    return str(self.tai_san_bao_tri)

quanlitaisan/forms.py
from django import forms
from django.forms import ModelForm
from .models import TaiSan, LichSuBaoTri 

forms.DateInput.input_type = 'date'


class FormTaiSan(ModelForm):
  class Meta:
    model = TaiSan
    fields = '__all__'
    widgets = {
        'ngay_su_dung': forms.DateInput()
    }


class FormTimKiemTaiSan(ModelForm):
  class Meta:
    model = TaiSan
    fields = ('loai_tai_san', 'ten_tai_san')


class FormBaoTri(ModelForm):
  class Meta:
    model = LichSuBaoTri
    fields = '__all__'

quanlitaisan/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import FormTaiSan, FormBaoTri, FormTimKiemTaiSan
from .models import TaiSan, LichSuBaoTri, NhanVien
from django.core.paginator import Paginator
from .api import FileExport
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings

def get_infor_by_user(request):
  user = request.user
  employee = list(NhanVien.objects.filter(user = user))[0]
  assets = TaiSan.objects.filter(quan_ly = employee)
  maintains = LichSuBaoTri.objects.filter(tai_san_bao_tri__quan_ly = employee)
  return {'assets' : assets, 'employee' : employee, 'maintains': maintains}

@login_required
def index(req):
  if req.user.is_superuser:
    assets = TaiSan.objects.all()
    maintains = LichSuBaoTri.objects.all()
    employee = list(NhanVien.objects.filter(user = req.user))[0]
  else:
    infor = get_infor_by_user(req)
    assets = infor['assets']
    maintains = infor['maintains']
    employee = infor['employee']

  # get last 5 assets and maintain
  if assets.count() > 5: 
    assets = reversed(assets[(len(assets)-5):])
  if maintains.count() > 5:
    maintains = reversed(maintains[(len(maintains)-5):]) 
  return render(req, 'quanlitaisan/base.html', {'assets': assets,'maintains' : maintains, 'title': 'Trang chủ', 'name': employee.name})

@login_required
def index_update(request):
  infor = get_infor_by_user(request)
  employee = infor['employee']
  return render(request, 'quanlitaisan/index1.html', {'title': 'Trang chủ', 'name': employee.name, 'page_name': 'Trang chủ'})

@login_required
def details(req, asset_id):
  # obj = TaiSan.objects.get(pk = asset_id)
  infor = get_infor_by_user(req)
  assets = infor['assets']
  employee = infor['employee']
  obj = get_object_or_404(TaiSan, pk = asset_id)
  child_assets = TaiSan.objects.filter(tai_san_cha  = asset_id)
  history = obj.lichsubaotri_set.all()
  context = {'obj' : obj, 'title': 'Chi tiết','child' : child_assets, 'history' : history, 'name' : employee.name}
  return render(req, 'quanlitaisan/detail.html', context)

@login_required
def maintains(request, maintain_id):
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  obj = LichSuBaoTri.objects.get(pk = maintain_id)
  return render(request, 'quanlitaisan/maintain_details.html',{'obj': obj, 'title': 'Chi tiết bảo trì','name' : employee.name})

@login_required
def assets_list(request, page):
  #add a comment
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  if employee.user.is_superuser:
    assets = TaiSan.objects.filter()
  
  paginator = Paginator(assets, 25)
  title = 'Danh sách tài sản'
  assets = paginator.get_page(page)
  return render(request, 'quanlitaisan/assets_list.html',{'assets': assets, 'title': title, 'name': employee.name})

@login_required
def remove_asset(request, asset_id):
  if not request.user.is_superuser:
    return HttpResponse('Access denied')
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  obj = TaiSan.objects.get(pk = asset_id)
  obj.delete() 
  context = {
        'url_name' : '/assets/1',
        'title' :'Xóa thành công',
        'name' : employee.name
      }
  return render(request, 'quanlitaisan/sucess_view.html', context)

@login_required
def search_items(request):
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  
  if request.GET:
    user_criteria = request.GET
    if request.user.is_superuser:
      q = TaiSan.objects.all()
    else:
      q = assets
    id = user_criteria.get('asset_id')
    loai_ts = user_criteria.get('loai_tai_san')
    ten_ts = user_criteria.get('ten_tai_san')  
    from_date = user_criteria.get('from_date')
    to_date = user_criteria.get('to_date')
    hien_trang_sd = user_criteria.get('hien_trang')
    if id:
      q = q.filter(id = id)
    if loai_ts:
      q = q.filter(loai_tai_san = loai_ts)
    if ten_ts:
      q = q.filter(ten_tai_san__icontains = ten_ts)
    if from_date:
      q = q.filter(ngay_su_dung__gte = from_date)
    if to_date:
      q = q.filter(ngay_su_dung__lte = to_date)
    if hien_trang_sd:
      q = q.filter(hien_trang = hien_trang_sd)

    FileExport.export_data = q

    return render(request, 'quanlitaisan/resultpage.html', {'obj': q, 'title': 'Kết quả tìm kiếm', 'name': employee.name})
  else:
    return render(request, 'quanlitaisan/search.html', { 'title': 'Tìm kiếm tài sản', 'name': employee.name})

@login_required
def add_asset(request):
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  if request.method == 'GET':
    form = FormTaiSan
    context = {
        'title' : 'Thêm tài sản',
        'form' : form,
        'name' : employee.name
    }
    return render(request, 'quanlitaisan/addItem.html', context)
  else:
    form = FormTaiSan(request.POST)
    if form.is_valid():
      user_data = form.cleaned_data
      new_item = TaiSan(**user_data)
      new_item.save()
      context = {
        'url_name' : '/addItem',
        'title' : 'Lưu tài sản thành công',
        'name' : employee.name
      }
      return render(request, 'quanlitaisan/sucess_view.html', context)
    return render(request, 'quanlitaisan/addItem.html', {'title': 'Invalid input', 'form' : form})

@login_required
def add_maintain(request):
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']

  if request.method == 'GET':
    form = FormBaoTri
    return render(request, 'quanlitaisan/addMaintain.html', {'form': form, 'title': 'Thêm bảo trì','name' : employee.name})

  else:
    form = FormBaoTri(request.POST)
    if form.is_valid():
      user_data = form.cleaned_data
      new_item = LichSuBaoTri(**user_data)
      new_item.save()

      context = {
        'url_name' : '/addMaintain',
        'title': 'Thêm thành công',
        'name' : employee.name
      }
      return render(request, 'quanlitaisan/sucess_view.html', context)
    else:
      return render(request, 'quanlitaisan/addMaintain.html', {'form': form, 'title': 'Invalid input'})


@login_required
def delete(request, asset_id):
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  if not request.user.is_superuser:
    return HttpResponse('Access denied')
  return render(request, 'quanlitaisan/delete_view.html', {'asset_id': asset_id, 'name': employee.name})

@login_required
def update_asset(request, asset_id):
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  if not request.user.is_superuser:
    return HttpResponse('Access denied')

  if request.method == 'GET':
    asset = TaiSan.objects.get(pk = asset_id)
    form = FormTaiSan(instance= asset)
    return render(request, 'quanlitaisan/update_form.html', {'form': form,'name': employee.name, 'title': 'Cập nhật thông tin'})
  else:
    asset = TaiSan.objects.get(pk = asset_id)
    update_infor = FormTaiSan(request.POST, instance = asset)
    update_infor.save()
    return render(request, 'quanlitaisan/sucess_view.html', {'title':'Cập nhật thành công', 'url_name': '/search'})



@login_required
def inspect(request):
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  if request.method == 'GET':
    return render(request, 'quanlitaisan/kiemke.html',{'title': 'Kiểm kê','name' : employee.name})
  
  else:    
    update_infor = request.POST
    print(update_infor)
    assets = update_infor.getlist('id')
    inspects = update_infor.getlist('inspect')
    
    success_item = 0
    failed_item = 0
    error_list = []
    for (id, inspect) in zip(assets, inspects):
      id = int(id)
      try:    
        asset = TaiSan.objects.get(pk = id)
        success_item +=1
      except:
        asset = None
        failed_item += 1
        error_list.append(id)
        # pass
      if asset:
        asset.so_luong = int(inspect)
        asset.save()
    context = {
      'url_name' : '/kiemke',
      'title' : 'Lưu dữ liệu thành công',
      'sucess' : success_item,
      'fail' : failed_item,
      'error_list': error_list
    }
    return render(request, 'quanlitaisan/update_sucess.html', context)

@login_required
def inspect_update(request):
  infor = get_infor_by_user(request)
  assets = infor['assets']
  employee = infor['employee']
  if request.method == 'GET':
    return render(request, 'quanlitaisan/kiemke_update.html',{'title': 'Kiểm kê vật tư thiết bị','page_name': 'Kiểm kê vật tư thiết bị','name' : employee.name})
  
  else:    
    update_infor = request.POST
    print(update_infor)
    assets = update_infor.getlist('id')
    data = update_infor.getlist('data')
    
    success_item = 0
    failed_item = 0
    error_list = []
    for (id, sl) in zip(assets, data):
      id = int(id)
      try:    
        asset = TaiSan.objects.get(pk = id)
        success_item +=1
      except:
        asset = None
        failed_item += 1
        error_list.append(id)
        # pass
      if asset:
        asset.so_luong = int(sl)
        asset.save()
    context = {
      'url_name' : '/kiemke',
      'title' : 'Lưu dữ liệu thành công',
      'sucess' : success_item,
      'fail' : failed_item,
      'error_list': error_list
    }
    return render(request, 'quanlitaisan/update_sucess.html', context)



@login_required      
def nhap_hang(request):
  if request.method == 'GET':
    return render(request, 'quanlitaisan/nhaphang.html', {'title': 'Nhập hàng'})
  elif request.method == 'POST':
    update_infor = request.POST
    print(update_infor)
    ids = update_infor.getlist('id')
    quantities = update_infor.getlist('quantity')
    del ids[0]
    del quantities[0]
    print(ids, quantities)
    for (id, quantity) in zip(ids, quantities):

quanlitaisan/templates/quanlitaisan/addMaintain.html
{% extends "quanlitaisan/base.html" %}
{% block content %}
  <h1>Thêm thông tin bảo trì mới</h1>
  <form action= '' method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Lưu dữ liệu">
  </form>
  {% endblock %}

quanlitaisan/templates/quanlitaisan/assets_list.html
{% extends "quanlitaisan/base.html" %}

{% block extra_css %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'quanlitaisan/css/result.css' %}">
{% endblock %}
{% block content %}
  <h1>Danh sách tài sản</h1>
  <div>
    <table>
      <tr>
        <th>Mã tài sản</th>
        <th>Loại tài sản</th>
        <th>Tên tài sản</th>
        <th>Ngày bắt đầu sử dụng</th>
        <th>Số năm sử dụng</th>
        <th>Hiện trạng</th>
      </tr>
      {% for item in assets %}
        <tr>
          <td>{{ item.id }}</td>
          <td> {{ item.get_loai_tai_san_display }} </td>
          <td><a href="{% url 'quanlitaisan:details' item.id %}"> {{ item.ten_tai_san }}</a></td>
          <td class="start_date">{{ item.ngay_su_dung }}</td>
          <td class="year">{{ item.thoi_gian_sd  }}</td>
          <td class="state">{{ item.get_hien_trang_display }}</td>
        </tr>
      {% endfor %}
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if assets.has_previous %}
                <a href="1">&laquo; first</a>
                <a href="{{ assets.previous_page_number }}">previous</a>
            {% endif %}

        <span class="current">
                Page {{ assets.number }} of {{ assets.paginator.num_pages }}.
        </span>
          {% if assets.has_next %}
              <a href="{{ assets.next_page_number }}">next</a>
              <a href="{{ assets.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
    </div>
  </div>
{% endblock %}

quanlitaisan/templates/quanlitaisan/detail.html
{% extends "quanlitaisan/base.html" %}

{% block extra_css %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'quanlitaisan/css/details.css' %}">
{% endblock %}
{% block content %}
<h2>Thông tin tài sản</h2>

<table id = 'detail_table'>
    <tr>
        <td>Mã tài sản:</td>
        <td>{{ obj.id }}</td>
      </tr>
  <tr>
    <td>Loại tài sản:</td>
    <td>{{ obj.get_loai_tai_san_display }}</td>
  </tr>
  <tr>
    <td>Tên tài sản:</td>
    <td> {{ obj.ten_tai_san }}</td>
  </tr>
  <tr>
    <td>Đơn vị:</td>
    <td> {{ obj.get_don_vi_tinh_display}}</td>
  </tr>
  <tr>
    <td>Số lượng:</td>
    <td> {{ obj.so_luong }}</td>
  </tr>
  <tr>
    <td>Ngày bắt đầu sử dụng:</td>
    <td>{{ obj.ngay_su_dung }}</td>
  </tr>
  <tr>
    <td>Thời gian sử dụng:</td>
    <td>{{ obj.thoi_gian_sd }}</td>
  </tr>
  <tr>
    <td>Thời hạn bảo hành:</td>
    <td>{{ obj.thoi_han_bao_hanh }}</td>
  </tr>
  <tr>
      <td>Địa điểm:</td>
      <td>{{ obj.dia_diem }}</td>
    </tr>
  <tr>
    <td>Trạng thái:</td>
    <td>{{ obj.get_hien_trang_display }}</td>
  </tr>
  <tr>
    <td>Người quản lý</td>
    <td>{{ obj.quan_ly.name }}</td>
  </tr>
  <tr>
    <td>Tài sản cha</td>
    {%if obj.tai_san_cha %}
      <td><a href="{% url 'quanlitaisan:details'  obj.tai_san_cha.id  %}">{{obj.tai_san_cha.ten_tai_san}}</a></td>
    {% else %}
      <td>None</td>
    {% endif %}
  </tr>
  <tr>
    <td>Tài sản con</td>
    <td>
      <div id="child_list">
        {%if child %}
          <ul>
          {% for asset in child %}
            <li><a href="{% url 'quanlitaisan:details' asset.id  %}">{{asset.ten_tai_san}}</a></li>
          {% endfor %}
          </ul>
        {% else %}
          None
        {% endif %}
      </div>
    </td>
  </tr>
  
</table>

<h2>Lịch sử bảo trì</h2>
{% if history %}
  <table>
    <tr>
      <th>Ngày bảo trì</th>
      <th>Nội dung tóm tắt</th>
    </tr>
    {% for entry in history %}
      <tr>
        <td>{{ entry.ngay_bao_tri }}</td>
        <td><a href="{% url 'quanlitaisan:maintains' entry.id %}">{{ entry.tieu_de}}</a></td>
      </tr>
    {% endfor %}
  </table>
{% else %}
<p>None</p>
{% endif %}
{% if user.is_superuser %}
<div class="ud">
    <a href="{% url 'quanlitaisan:update' obj.id %}">Sửa thông tin tài sản</a> <br>
  </div>
  
  <div class="ud">
    <a href="{% url 'quanlitaisan:delete_view' obj.id %}">Xóa tài sản</a>
  </div>
{% endif %}
{% endblock %}

quanlitaisan/templates/quanlitaisan/maintain_details.html
{% extends 'quanlitaisan/base.html' %}

{% block extra_css %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'quanlitaisan/css/maintainDetails.css' %}">
{% endblock %}
{% block content %}
  <h2>Chi tiết bảo trì</h2>
  <table>
    <tr>
      <td>Ngày bảo trì</td>
      <td>{{ obj.ngay_bao_tri }}</td>
    </tr>
    <tr>
      <td>Tài sản bảo trì</td>
      <td><a href="{% url 'quanlitaisan:details' obj.tai_san_bao_tri.id %}">{{ obj.tai_san_bao_tri.ten_tai_san }}</a></td>
    </tr>
    <tr>
      <td>Tiêu đề</td>
      <td>{{ obj.tieu_de}}</td>
    </tr>
    <tr>
      <td>Nội dung</td>
      <td>{{ obj.noi_dung}}</td>
    </tr>
  </table>
{% endblock %}

quanlitaisan/templates/quanlitaisan/nhaphang_update.html
{% extends "quanlitaisan/capnhatsl.html" %}
{% block submit %}
/nhap/
{% endblock %}

quanlitaisan/templates/quanlitaisan/pagination_test.html
{% for contact in contacts %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.full_name|upper }}<br>
    ...
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
            <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

quanlitaisan/templates/quanlitaisan/profile.html
{% extends 'quanlitaisan/base.html' %}
{% block extra_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'quanlitaisan/css/profile.css' %}">
{% endblock %}
{% block content %}
<h2>Thông tin nhân viên</h2>
<table id="details_table">
    <tr>
        <th>Họ và tên:</th>
        <td>{{ emp.name }}</td>
    </tr>
    <tr>
        <th>Chức vụ:</th>
        <td>{{ emp.title }}</td>
    </tr>
    <tr>
        <th>Phòng ban:</th>
        <td>{{ emp.department }}</td>
    </tr>
</table>
<p>
    <ul>
        <li>
            <a href="/changepassword/">Đổi mật khẩu</a><br>
        </li>
        <li>
            <a href="/signout">Đăng xuất</a>
        </li>
    </ul>
</p>
{% endblock %}

quanlitaisan/templates/quanlitaisan/resultpage.html
{% extends "quanlitaisan/base.html" %}

{% block extra_css %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'quanlitaisan/css/result.css' %}">
{% endblock %}

{% block content %}
  <h1>Kết quả tìm kiếm</h1>
  
  {%if obj|length > 0 %}
    <!-- <ul>
      {% for item in obj %}
       <li><a href="{% url 'quanlitaisan:details' item.id %}"> {{ item.ten_tai_san }}</a></li>
      {% endfor %}
    </ul> -->

      <table>
          <tr>
            <th class="id">Mã tài sản</th>
            <th class="id">Loại tài sản</th>
            <th>Tên tài sản</th>
            <th class="start_date">Ngày bắt đầu sử dụng</th>
            <th class="year">Số năm sử dụng</th>
          </tr>
          {% for item in obj %}
            <!-- <li><a href="{% url 'quanlitaisan:details' item.id %}"> {{ item.ten_tai_san }}</a></li> -->
          <tr>
            <td class="id">{{ item.id }}</td>
            <td >{{ item.get_loai_tai_san_display }}</td>
            <td><a href="{% url 'quanlitaisan:details' item.id %}"> {{ item.ten_tai_san }}</a></td>
            <td class="start_date">{{ item.ngay_su_dung }}</td>
            <td class="year">{{ item.thoi_gian_sd  }}</td>
          </tr>
          {% endfor %}
        </table>
    <br>
    <div>
      <a href="/api/export/">Xuat du lieu</a>
    </div>
  {% else %}
    <p>Không tìm thấy kết quả nào</p>
  {% endif %}
{% endblock %}

quanlitaisan/templates/quanlitaisan/search.html
{% extends "quanlitaisan/base.html" %}
{% block extra_css %}
  {% load static %}
    <link rel="stylesheet" href="{% static 'quanlitaisan/css/search.css' %}">
{% endblock %}
{% block content %}
<h1>Tìm kiếm</h1>
<form action= '' method="GET">
  <!-- {% csrf_token %} -->
  <p>
    <label for="asset_id"> ID tài sản: </label>
    <input type="number" name="asset_id" >
  </p>
  <p>
    <label for="id_loai_tai_san">Loại tài sản:</label> 
    <select name="loai_tai_san" id="id_loai_tai_san">
    <option value="" selected>---------</option>
  
    <option value="VT">Vật tư</option>
  
    <option value="TB">Thiết bị</option>
  
    </select>
  </p>
  <p>
    <label for="id_ten_tai_san">Tên tài sản:</label> 
    <input type="text" name="ten_tai_san" maxlength="20" id="id_ten_tai_san">
  </p>
  <p>Thời gian bắt đầu sử dụng:</p>
  <div class='moreback'>
    <p>
      <label for="id_from_date">Từ ngày:</label> 
      <input type="date" name="from_date" maxlength="20" id="id_from_date">
    </p>
    <p>
      <label for="id_to_date">Đến ngày:</label> 
      <input type="date" name="to_date" maxlength="20" id="id_to_date">
    </p>
  </div>
  <p>
    <label for="id_hien_trang">Hiện trạng:</label> 
    <select name="hien_trang" id="id_hien_trang">
        <option value="" selected>---------</option>
      
        <option value="SD">Sử dụng</option>
      
        <option value="BH">Bị hỏng</option>
      
    </select>
  </p>
  <!-- {{form.as_p}} -->
  <input type="submit" name="Search" value = "Tìm kiếm" id="">

</form>
{% endblock %}

quanlitaisan/templates/quanlitaisan/sucess_view.html
{% extends "quanlitaisan/base.html" %}
{% block title %} Lưu thành công {% endblock %}
{% block extra_css %}
  {% load static %}
    <link rel="stylesheet" href="{% static 'quanlitaisan/css/success.css' %}">
{% endblock %}
{% block content %}
  <div id="save_respone"> 
    {% block extra_content %}
    {% endblock %}
    <h2> Đã lưu vào cơ sở dữ liệu. Bạn có muốn tiếp tục ? </h2>
    <div id= "links">
      <a id="back" href="/"> Quay lại trang chủ </a>
      {%if url_name %}
        <a id="continue" href={{ url_name }}>Tiếp tục </a>  
      {% endif %}
    </div>
  </div>
{% endblock %}

quanlitaisan/templates/quanlitaisan/update_form.html
{% extends 'quanlitaisan/base.html' %}
{% block content %}
<h2>Sửa thông tin</h2>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" value="Cập nhật"></p>
</form>
  {% endblock %}

quanlitaisan/templates/quanlitaisan/xuathang.html
{% extends "quanlitaisan/capnhatsl.html" %}
{% block submit %}
/xuat/
{% endblock %}